name: Build Flutter APK on macOS and Publish Release

on:
  push:
    branches:
      - main  # Change this to your desired branch
  release:
    types:
      - created

jobs:
  build:
    name: Build APK on macOS
    runs-on: macos-latest  # Running on macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter on macOS
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create Release on macOS
    needs: build
    runs-on: macos-latest
    if: github.event_name == 'release'

    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: flutter-apk
          path: app-release.apk

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          assets: "app-release.apk"
