name: Flutter Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Flutter
        run: |
          curl -fsSL https://sdk.flutter.dev/channels/stable/android-stable/latest/install-flutter-macos-stable.sh -o install-flutter-macos-stable.sh
          bash install-flutter-macos-stable.sh

      - name: Configure Flutter
        run: flutter config --enable-flutter-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v{{ github_ref }}
          name: Flutter Release {{ github_ref }}
          body: This is a release for Flutter app version {{ github_ref }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
